### ISSUE TITLE
Create network socket

### ISSUE THREAD

**Issue by sybux** [TeemIp/teemip-cable-mgmt#5]
Hi,

i'm running all latest version of a fresh iTop 3.1.1-1-12561 and extenstions installation as :
Network Management Extended
Datacenter view extended
IPAM for iTOP
...

In the patch panel module, I don't have option to create network socket in the drop-down menu.
I've check in configuration and the section
	'teemip-cable-mgmt' => array (
		'find_wiring_paths' => array (
		  'max_rack_levels_to_cross' => 5,
		  'max_offers_to_display' => 32,
		),
	),
is present. 

So if you can point me how to get this option back.

Support information below :
```
  ===== begin =====
  iTopVersion: 3.1.1-1
  iTopBuild: 12561
  iTopBuildDate: 2023-12-19 10:53:23
  MySQLVersion: 8.0.39-0ubuntu0.24.04.1
  PHPVersion: 8.3.6
  OSVersion: Linux
  WebServerVersion: Apache/2.4.58 (Ubuntu)
  PHPModules: Core, date, libxml, openssl, pcre, zlib, filter, hash, json, random, Reflection, SPL, session, standard, sodium, apache2handler, mysqlnd, PDO, xml, bz2, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, iconv, ldap, exif, mcrypt, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, soap, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, zip, Zend OPcache
  ItopSetting/cron_max_execution_time: 600
  ItopSetting/timezone: Europe/Paris
  PHPSetting/memory_limit: 128M
  PHPSetting/max_execution_time: 30
  PHPSetting/upload_max_filesize: 2M
  PHPSetting/post_max_size: 8M
  MySQLSetting/max_allowed_packet: 268435456
  MySQLSetting/key_buffer_size: 16777216
  MySQLSetting/query_cache_size: 
  MySQLStatus/Key_read_requests: 0
  MySQLStatus/Key_reads: 0
  InstallDate: 2024-08-14 16:58:06
  InstallPath: /var/www/html/
  ---- Installation choices ----
  InstalledExtension/itop-config-mgmt-core/3.1.1-1
  InstalledExtension/itop-config-mgmt-datacenter/3.1.1-1
  InstalledExtension/itop-config-mgmt-end-user/3.1.1-1
  InstalledExtension/itop-config-mgmt-storage/3.1.1-1
  InstalledExtension/itop-config-mgmt-virtualization/3.1.1-1
  InstalledExtension/itop-service-mgmt-enterprise/3.1.1-1
  InstalledExtension/itop-ticket-mgmt-none/3.1.1-1
  InstalledExtension/itop-change-mgmt-simple/3.1.1-1
  InstalledExtension/itop-kown-error-mgmt/3.1.1-1
  InstalledExtension/itop-problem-mgmt/3.1.1-1
  InstalledExtension/combodo-data-collector-for-vsphere/1.2.0 (iTop Hub)
  InstalledExtension/teemip-network-mgmt-extended/3.1.2 (iTop Hub)
  InstalledExtension/molkobain-datacenter-view/1.13.0 (iTop Hub)
  InstalledExtension/molkobain-datacenter-view-extended-bridge-for-teemip/1.5.0 (iTop Hub)
  InstalledExtension/teemip-cable-mgmt/1.2.0 (iTop Hub)
  InstalledExtension/molkobain-datacenter-view-extended/1.10.0 (iTop Hub)
  InstalledExtension/combodo-vsphere-datamodel/1.0.0 (iTop Hub)
  InstalledExtension/teemip-core-ip-mgmt/3.1.4 (iTop Hub)
  ---- Actual modules installed ----
  InstalledModule/authent-cas: 3.1.1
  InstalledModule/authent-external: 3.1.1
  InstalledModule/authent-ldap: 3.1.1
  InstalledModule/authent-local: 3.1.1
  InstalledModule/combodo-backoffice-darkmoon-theme: 3.1.1
  InstalledModule/combodo-password-expiration: 1.0.1
  InstalledModule/itop-attachments: 3.1.1
  InstalledModule/itop-backup: 3.1.1
  InstalledModule/itop-config: 3.1.1
  InstalledModule/itop-data-collector-vsphere: 1.2.0
  InstalledModule/itop-files-information: 3.1.1
  InstalledModule/itop-portal-base: 3.1.1
  InstalledModule/itop-profiles-itil: 3.1.1
  InstalledModule/itop-sla-computation: 3.1.1
  InstalledModule/itop-structure: 3.1.1
  InstalledModule/itop-themes-compat: 3.1.1
  InstalledModule/itop-tickets: 3.1.1
  InstalledModule/itop-welcome-itil: 3.1.1
  InstalledModule/molkobain-fontawesome5-pack: 1.5.1
  InstalledModule/molkobain-handy-framework: 1.10.2
  InstalledModule/molkobain-newsroom-provider: 1.5.0
  InstalledModule/authent-token: 2.1.3
  InstalledModule/combodo-db-tools: 3.1.1
  InstalledModule/itop-config-mgmt: 3.1.1
  InstalledModule/itop-core-update: 3.1.1
  InstalledModule/itop-datacenter-mgmt: 3.1.1
  InstalledModule/itop-endusers-devices: 3.1.1
  InstalledModule/itop-faq-light: 3.1.1
  InstalledModule/itop-hub-connector: 3.1.1
  InstalledModule/itop-knownerror-mgmt: 3.1.1
  InstalledModule/itop-oauth-client: 3.1.1
  InstalledModule/itop-problem-mgmt: 3.1.1
  InstalledModule/itop-service-mgmt: 3.1.1
  InstalledModule/itop-storage-mgmt: 3.1.1
  InstalledModule/itop-virtualization-mgmt: 3.1.1
  InstalledModule/molkobain-console-tooltips: 1.3.0
  InstalledModule/molkobain-datacenter-view: 1.13.0
  InstalledModule/teemip-framework: 3.1.4
  InstalledModule/teemip-network-mgmt: 3.1.1
  InstalledModule/combodo-vsphere-datamodel: 1.0.0
  InstalledModule/combodo-webhook-integration: 1.3.2
  InstalledModule/itop-bridge-cmdb-services: 3.1.1
  InstalledModule/itop-bridge-cmdb-ticket: 3.1.1
  InstalledModule/itop-bridge-datacenter-mgmt-services: 3.1.1
  InstalledModule/itop-bridge-endusers-devices-services: 3.1.1
  InstalledModule/itop-bridge-storage-mgmt-services: 3.1.1
  InstalledModule/itop-bridge-virtualization-mgmt-services: 3.1.1
  InstalledModule/itop-bridge-virtualization-storage: 3.1.1
  InstalledModule/itop-change-mgmt: 3.1.1
  InstalledModule/molkobain-datacenter-view-extended: 1.10.0
  InstalledModule/teemip-ip-mgmt: 3.1.2
  InstalledModule/teemip-ipv6-mgmt: 3.1.2
  InstalledModule/teemip-newsroom-provider: 1.1.2
  InstalledModule/teemip-webservices: 3.0.0
  InstalledModule/teemip-config-mgmt-adaptor: 3.1.1
  InstalledModule/teemip-datacenter-mgmt-adaptor: 3.1.1
  InstalledModule/teemip-endusers-devices-adaptor: 3.1.0
  InstalledModule/teemip-network-mgmt-extended: 3.1.2
  InstalledModule/teemip-storage-mgmt-adaptor: 3.1.0
  InstalledModule/teemip-virtualization-mgmt-adaptor: 3.1.2
  InstalledModule/molkobain-datacenter-view-extended-bridge-for-teemip: 1.5.2
  InstalledModule/teemip-bridge-virtualization-network-extended: 3.0.1
  InstalledModule/teemip-cable-mgmt: 1.2.0
  InstalledModule/teemip-bridge-datacenter-view-extended-cable: 1.1.0
  InstalledModule/teemip-bridge-network-extended-cable: 1.1.0
  ===== end =====  
```
